# Site settings
title: QuickHelper Project
description: An innovative mobile app to assist people and encourage effective communication
url: "https://andyfengc.github.io/QuickHelper-server/"
port: 4001

# Author settings
author:
  name     : Andy Feng
  bio      : Full-stack Developer with 10+ years of experience using .Net, Java, Javascript. I am passionate about new IT technologies.
  email    : andyfengc@gmail.com

#SEO settings
logo: /assets/img/img-blog.png/ # Site logo URL

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed