# Site settings
title: QuickHelper Project
description: a IT guy's blog
baseurl: "/QuickHelper-server"
url: "https://github.com/andyfengc" 
server_url: http://quickhelperserver-andyfengc.rhcloud.com/quickhelper
author: 
  name: Andy Feng
  github: https://github.com/andyfengc
  website: https://andyfengc.github.io

port: 4001

markdown: kramdown
highlighter: rouge
github_username:  andyfengc

# based on Tom Preston-Werner http://tom.preston-werner.com/